"""Add branch_id and bid_type to NotificationRule

Revision ID: 0c2595e3a1fd
Revises: 8ed0f363d54e
Create Date: 2026-02-12 16:19:38.091677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2595e3a1fd'
down_revision = '8ed0f363d54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_constraint('design_designer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'designer', ['designer_id'], ['id'])

    with op.batch_alter_table('estimator', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('notification_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bid_type', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['branch_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'designer', ['designer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notification_rule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bid_type')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('estimator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('design_designer_id_fkey', 'estimator', ['designer_id'], ['estimatorID'])

    # ### end Alembic commands ###
