"""Add ITService table

Revision ID: 3ca35f57f7f4
Revises: 31081991b1e3
Create Date: 2024-10-23 23:44:14.070874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca35f57f7f4'
down_revision = '31081991b1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('it_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_type', sa.String(length=255), nullable=False),
    sa.Column('createdby', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('updatedby', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    op.drop_table('it_service')
    # ### end Alembic commands ###
