"""Add related tables for Framing, Siding, etc. with cascading deletes and indexing

Revision ID: 67a0a2ddbbaa
Revises: c0de8b539287
Create Date: 2024-11-30 18:37:39.494252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a0a2ddbbaa'
down_revision = 'c0de8b539287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for cascading deletes and indexing ###

    op.create_table('deck',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('decking_type', sa.String(length=50), nullable=False),
    sa.Column('railing_type', sa.String(length=50), nullable=False),
    sa.Column('stairs', sa.String(length=50), nullable=False),
    sa.Column('deck_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_id_on_deck', 'deck', ['project_id'])

    op.create_table('door',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('door_notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_id_on_door', 'door', ['project_id'])

    op.create_table('framing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=50), nullable=False),
    sa.Column('lot_type', sa.String(length=50), nullable=False),
    sa.Column('basement_wall_height', sa.String(length=50), nullable=True),
    sa.Column('basement_exterior_walls', sa.String(length=50), nullable=False),
    sa.Column('basement_interior_walls', sa.String(length=50), nullable=False),
    sa.Column('floor_framing', sa.String(length=50), nullable=False),
    sa.Column('floor_sheeting', sa.String(length=50), nullable=False),
    sa.Column('floor_adhesive', sa.String(length=50), nullable=False),
    sa.Column('exterior_walls', sa.String(length=50), nullable=False),
    sa.Column('first_floor_wall_height', sa.String(length=50), nullable=False),
    sa.Column('second_floor_wall_height', sa.String(length=50), nullable=True),
    sa.Column('wall_sheeting', sa.String(length=50), nullable=False),
    sa.Column('roof_trusses', sa.String(length=50), nullable=False),
    sa.Column('roof_sheeting', sa.String(length=50), nullable=False),
    sa.Column('framing_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_id_on_framing', 'framing', ['project_id'])

    op.create_table('shingle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('shingle_notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_id_on_shingle', 'shingle', ['project_id'])

    op.create_table('siding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('lap_type', sa.String(length=50), nullable=False),
    sa.Column('panel_type', sa.String(length=50), nullable=False),
    sa.Column('shake_type', sa.String(length=50), nullable=False),
    sa.Column('soffit_trim', sa.String(length=50), nullable=False),
    sa.Column('window_trim_detail', sa.String(length=50), nullable=False),
    sa.Column('siding_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_id_on_siding', 'siding', ['project_id'])

    op.create_table('trim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('base', sa.String(length=50), nullable=False),
    sa.Column('case', sa.String(length=50), nullable=False),
    sa.Column('stair_material', sa.String(length=50), nullable=False),
    sa.Column('door_material_type', sa.String(length=50), nullable=False),
    sa.Column('number_of_panels', sa.String(length=50), nullable=False),
    sa.Column('door_hardware', sa.String(length=50), nullable=False),
    sa.Column('built_in_materials_type', sa.String(length=50), nullable=False),
    sa.Column('plywood_1x_count', sa.String(length=50), nullable=True),
    sa.Column('specify_count', sa.String(length=50), nullable=False),
    sa.Column('trim_allowance', sa.String(length=50), nullable=True),
    sa.Column('trim_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_id_on_trim', 'trim', ['project_id'])

    op.create_table('window',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('window_notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_id_on_window', 'window', ['project_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted for cascading deletes and indexing ###
    op.drop_index('idx_project_id_on_window', table_name='window')
    op.drop_table('window')
    op.drop_index('idx_project_id_on_trim', table_name='trim')
    op.drop_table('trim')
    op.drop_index('idx_project_id_on_siding', table_name='siding')
    op.drop_table('siding')
    op.drop_index('idx_project_id_on_shingle', table_name='shingle')
    op.drop_table('shingle')
    op.drop_index('idx_project_id_on_framing', table_name='framing')
    op.drop_table('framing')
    op.drop_index('idx_project_id_on_door', table_name='door')
    op.drop_table('door')
    op.drop_index('idx_project_id_on_deck', table_name='deck')
    op.drop_table('deck')
    # ### end Alembic commands ###
