"""Add square_footage to Design

Revision ID: 8ed0f363d54e
Revises: fea987654321
Create Date: 2026-02-04 16:50:32.166216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed0f363d54e'
down_revision = 'fea987654321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('square_footage', sa.Integer(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['sales_rep_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_column('square_footage')

    # ### end Alembic commands ###
