"""Add Project model

Revision ID: c0de8b539287
Revises: 03adb408fbb3
Create Date: 2024-11-30 18:14:52.916039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0de8b539287'
down_revision = '03adb408fbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('contractor', sa.String(length=255), nullable=False),
    sa.Column('project_address', sa.String(length=255), nullable=False),
    sa.Column('contractor_phone', sa.String(length=15), nullable=True),
    sa.Column('contractor_email', sa.String(length=255), nullable=True),
    sa.Column('include_framing', sa.Boolean(), nullable=False),
    sa.Column('include_siding', sa.Boolean(), nullable=False),
    sa.Column('include_shingles', sa.Boolean(), nullable=False),
    sa.Column('include_deck', sa.Boolean(), nullable=False),
    sa.Column('include_doors', sa.Boolean(), nullable=False),
    sa.Column('include_windows', sa.Boolean(), nullable=False),
    sa.Column('include_trim', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_by', sa.String(length=150), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_rep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
