"""added foreign keys for users

Revision ID: cc0d1f788bac
Revises: 38c9830b0e51
Create Date: 2024-07-22 14:12:06.852971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0d1f788bac'
down_revision = '38c9830b0e51'
branch_labels = None
depends_on = None

def upgrade():
    # Ensure we are in a batch operation if using SQLite
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Create foreign keys within the batch operation
        batch_op.create_foreign_key('fk_user_usertype_id', 'user_type', ['usertype_id'], ['id'])
        batch_op.create_foreign_key('fk_user_estimatorID', 'estimator', ['estimatorID'], ['estimatorID'])
        batch_op.create_foreign_key('fk_user_sales_rep_id', 'sales_rep', ['sales_rep_id'], ['id'])
        batch_op.create_foreign_key('fk_user_branch_id', 'branch', ['user_branch_id'], ['branch_id'])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_branch_id', 'user', type_='foreignkey')
    op.drop_constraint('fk_user_sales_rep_id', 'user', type_='foreignkey')
    op.drop_constraint('fk_user_estimatorID', 'user', type_='foreignkey')
    op.drop_constraint('fk_user_usertype_id', 'user', type_='foreignkey')

