from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# Revision identifiers, used by Alembic.
revision = 'manual_initial'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerCode', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customerCode')
    )
    op.create_table('estimator',
    sa.Column('estimatorID', sa.Integer(), nullable=False),
    sa.Column('estimatorName', sa.String(length=100), nullable=False),
    sa.Column('estimatorUsername', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('estimatorID')
    )
    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('estimator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['estimator_id'], ['estimator.estimatorID'], name='fk_estimator_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planNumber', sa.String(length=10), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('project_address', sa.String(length=200), nullable=False),
    sa.Column('contractor', sa.String(length=100), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('preliminary_set_date', sa.DateTime(), nullable=True),
    sa.Column('designer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('plan_description', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['designer_id'], ['estimator.estimatorID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planNumber')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('usertype', sa.String(length=50), nullable=False),
    sa.Column('estimatorID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estimatorID'], ['estimator.estimatorID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('design')
    op.drop_table('bid')
    op.drop_table('estimator')
    op.drop_table('customer')
    # ### end Alembic commands ###
